[package]
name = "central_server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
rayon = "1.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shared_resources = { path = "../shared_resources" }
rand = "0.10.0-rc.5"

