[package]
name = "shared_resources"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"
chrono = "0.4.42"
uuid = { version = "1.3", features = ["v4", "serde"] }