[package]
name = "gas_station"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.145"
shared_resources = { version = "0.1.0", path = "../shared_resources" }
uuid = { version = "1.3", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }