[package]
name = "regional_server"
version = "0.1.0"
edition = "2024"

[dependencies]
shared_resources = { path = "../shared_resources" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
